### ISSUE TITLE
Specify GID other than "0" produces console error

### ISSUE THREAD

**Issue by mmeiers** [GoogleWebComponents/google-sheets#14] opened 2015-03-18 14:04 UTC
When Specifying a gid other than gid="0" for example: gid="1944964720" I get the following error in console and do not get back any data. 

XMLHttpRequest cannot load https://spreadsheets.google.com/feeds/list/1rVmJWbWUyr-xNWw-FJNDUHEGHL_UgNpIDcwxmNH0RR8/w5z7e2/public/values?alt=json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:59816' is therefore not allowed access. The response had HTTP status code 400.

Works fine with the same spreadsheet and pulling from first tab which is gid="0".

**Comment by ebidel** [comment] 2015-03-18 16:34
Dupe of https://github.com/GoogleWebComponents/google-sheets/issues/13

**Closed by ebidel** 2015-03-18 16:34 UTC
